apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-service-config
  namespace: homie
data:
  TASK_SERVICE_URL: "http://task-service:8080"
  REDIS_URL: "redis://192.168.0.253:6379"
  CRON_SCHEDULE: "* * * * *"
