apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: homie
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.image.repository }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TASK_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: TASK_SERVICE_URL
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: REDIS_URL
            - name: CRON_SCHEDULE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: CRON_SCHEDULE
          resources:
            {{- toYaml .Values.resources | nindent 12}}