replicaCount: 1

image:
  repository: 192.168.0.253:5050/task-service
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 8081
  nodePort: 30081

env:
  HTTP_PORT: "8081"
  JWT_EXPIRY: "24h"

secret:
  databaseUrl: ""
  jwtSecret: ""

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
