---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auth-service-secret
  namespace: homie
spec:
  encryptedData:
    database-url: AgCDxU29l4BK7n+9wMyWr0deFU7BOwBEzNzQGyZSifnSJSs4qc1XYQkcX9+ePSToHMo9zNL+Yz688yFChoGFzwK/LrPS62R8VHb7jhOYiHtX+hMQvfcumUAcDSE2T2+U3sqMJkdYRLjhQ73A0hk4+kALjXSN/qYx8imeZz1gPln2dUbb6+wFcvCfdCabK/hyR+IPEbIGtaLrgPBodQSuZE3b/hbqi/uSVHAOMd1mRjPeDLwF79xZFbjpWYb8XCP7P1zjTOV0INN7LTHqUXd6G0fTIc5Kd96tv2Zxp9/z4TTeySKwrZPisxcj348d3okNscrv0m4yJAyGdvs93aavzdzyokXLgzVVJlD/Mi3OH0wTJGNBf8RRUUgjNKEAXSwGD/jtJsRKgKk9E7pj2LjP51yD1WCTEO2QleUMT3wNHcfE2va9jawgeRIh4O6tbAoIuxTu81wtlRwWlxswKnhTWCy6ljtsec7qe4pw3dS1ZUI/m7ISolyMA3iwYYg4Pob/QzJ781IWEXgEVCsPwBFpNen0jwUos6BrRFXvJdNyVHO+7/qqAyGnpImL9HyqKD9yVn1eUN+YEvu7zE7UxWd9I8hEPD8Kx6bTpprZir0XnXbBn35zDKYOUdPL9lZRfDCfJQE9naXx3GORuGouT1h98mhKxbUTKrYTwNKTps6uAbiYXRiSSG36dARZemyYZP9jw38oIMbZ0Y15ZT/sb21xkzj//UOIcUYm+OeomAEsqhVW3ufpgAAKUS7NspSXID2nhqDJK98jU1REdmN4QA==
    jwt-secret: AgBz9hAxuNCP1GWFtmCz1EfB7v+QyYx3Sql6U/OVA6Fi5iVMWKxpndw7T2VfuzyBCT/GaAx/DMLT4skIAlbiEhqZ5HqcHl0OxiF/80/KQDsgzHgcLsbzKO3/BrjM9W1kwwsq1FTvURXq3Oqk/8v15mU2LYXa+kXS7RkAyHj4fsMgWbmHcMm3+ejUyOfxoUhmJUoxaoPzQlOnZ65Wzhnl/rPDtCWR60kbd4a33MAP7gokhHVdfGqSobJDTBnGB3A86zPicT8XfJhbmvmuo2RDTvXc7zUqUmIVCiky/Vk9YC+Kn+GbLsCLU4GKdtkKnEsCwzChsgmHuUoMPCV9990d+CYq8+zFo5uxZs534h6jR86TAjEk5NLBuHR4kSwgNvsg8xA4RCWlIduthtnAetQ+Cvigcml06QhGt81ESiDLyNfzb1LpThgoLe1mPqMiQuxifxCljIcv5FBXKFLMi2KtSNS++puupOp4Q1W2UuHYrEv1TEmXwM4d+GMHpT0mgea6Oc7SszxGuFn0Qa/HGFeAU1l10LEW7pgjAscFyHLjS5ACOnuliUF+0avqzT8jIKzZ6OycG68kFkLrJj3EAj/O44CWUfwVdNja6qGCHLWVyxpjOkjnVBnhT3PFUHwGTL4pPi+1bN3BFB+ephxkmGql+5Muuchu2+X9Igp9dnoMuO4OoSV99U9x8RdF/q4fCt0AlX7lEHQgKyl6xTibuFjNkguPN/NrSMPVlMMePW7iI8HGbV8pvVHqhKU9A9wSdYoyGpDVOa/u+jHiCbfPh6NtNRc9
  template:
    metadata:
      creationTimestamp: null
      name: auth-service-secret
      namespace: homie
