---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: task-service-secret
  namespace: homie
spec:
  encryptedData:
    database-url: AgBAe1nH/nANKc2trMB5NZaWUPL6qlKVOygesZPUm1+OHXXDl9UfnGYtjYnqEDExZx4KaD9khO1evufxtTgnEEKFEN9oCRtv1OwYYL/J4fpPK+YQcgiunskRJgHyP/+jcY+t4wymTPiXddfjHBGdN+aoVuGl/E67KQDx3neRgEQWBVlhVop4LirsOe6xMPMiQ5hrEd7iQ1KdHUS/HNy1yG+swQKU0oGScj2yMa0U/k6FmhGjC6DHiDtUKFpK7mGH+kPwJsCiOOLSZEvZ/1ST0gk4QPxLO4aOGQ1DzPcT9BYe6yNIiFaWvlMTGs/n3XuH03YMm2anuLeTaPRBkBrEDFzAvB756Xfh/j1Kz/K3YAUnbrZcbcsTk0fH+eP4CXOCVy9Zgf5cnxEdQbaqYL4JjBXGRUDeclYtiKAesINb9QbHgW2MJNzp+DLGkJchtW5k/AQLODeFnhiMS4td8wMCK1kNwVteX6xS74TPzq3bDmw7X/FYMZ4w3hWjLFz/KwRrBwJnv8+GXttxw4BODbkAHeS1sGhkTa0zuTPLFUaYTST2EZ4yq05dxH3Di2HAefPLsJW6vK71ARuQ+8GGSnoiF6qhS/PtHOr+pvbvSSDHjzPXKE0fA9B38N5wXs+4MOkIBk3OoFAg4Tn60fw6nMLLvItkoXueiKkp/sNixWXqoBfgb6cacq8J5ajHEmZ5kGsO2yFPMExJWWN9lgYrRL53BWw4Y1uHAZs3s9tECtIErb2NN215EPY3U5lDoo7FSzkb0Ee+kceKgaD/7aVtDw==
  template:
    metadata:
      creationTimestamp: null
      name: task-service-secret
      namespace: homie
